### PR TITLE
Update event system

### PR DESCRIPTION
**Pull request by S3v3Nice**
* Move all functionality of Events::Effective to Events (leave only the event classes, remove the structures)
* Remove INativeEvent & NativeEventIsCancelledManager

### CODE REVIEW

**Comment by S3v3Nice** [comment]
I had to add the /bigobj option, because Event.obj became too big, and the error "C1128: number of sections exceeded object file format limit: compile with /bigobj" began to appear.

**Comment by S3v3Nice** [comment]
By the way, to solve the problem of exceeding the section number limit without /bigobj option, I think you can only divide the classes of events into files (.hpp and .cpp for each event class).

**Comment by Pd233** [comment]
Using multiple cpp files can solve this problem. And the old event template class has some unnecessary forwarding, maybe it needs some optimization?

**Comment by S3v3Nice** [comment]
> And the old event template class has some unnecessary forwarding, maybe it needs some optimization?

Maybe. Could you specify what can be optimized?

**Comment by Pd233** [comment]
> Maybe. Could you specify what can be optimized?

Some short functions, such as event type casting methods between native event and managed event.
I will finish it after this PR was merged.  :D

**Comment by S3v3Nice** [comment]
> I will finish it after this PR was merged.

So it's not necessary to create cpp files for the events yet? Leave it that way for now, with /bigobj?

**Comment by Pd233** [comment]
> So it's not necessary to create cpp files for the events yet? Leave it that way for now, with /bigobj?

Creating headers and cpp files for all event class is a huge workload, so just using /bigobj for now.
It took me the whole afternoon when I write these event classes for the first time.  :(

**Review by Pd233 — APPROVED** [review]

**Pull request merged**
